<?php
/*
 * GBALib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GBALib\Tests;

use GBALib\APIException;
use GBALib\Exceptions;
use GBALib\APIHelper;
use GBALib\Models;

class MApiMobileClientsControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \GBALib\Controllers\MApiMobileClientsController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass()
    {
        $client = new \GBALib\GBAClient();
        self::$controller = $client->getMApiMobileClients();
    }

    /**
     * Setup test
     */
    protected function setUp()
    {
        $this->httpResponse = new HttpCallBackCatcher();
    }

    /**
     * Todo Add description for test testGetProfile
     */
    public function testGetProfile()
    {

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->getProfile();
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }
}
