<?php
/*
 * GBALib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GBALib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MRequest2 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $rating public property
     */
    public $rating;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $comment public property
     */
    public $comment;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $rating  Initialization value for $this->rating
     * @param string  $comment Initialization value for $this->comment
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->rating  = func_get_arg(0);
            $this->comment = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['rating']  = $this->rating;
        $json['comment'] = $this->comment;

        return $json;
    }
}
