<?php
/*
 * GBALib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GBALib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var array $comments public property
     */
    public $comments;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $comments Initialization value for $this->comments
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->comments = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['comments'] = $this->comments;

        return $json;
    }
}
