<?php
/*
 * GBALib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GBALib;

use GBALib\Controllers;

/**
 * GBALib client class
 */
class GBAClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $oAuthAccessToken = null
    ) {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
    /**
     * Singleton access to MApiMobileComments controller
     * @return Controllers\MApiMobileCommentsController The *Singleton* instance
     */
    public function getMApiMobileComments()
    {
        return Controllers\MApiMobileCommentsController::getInstance();
    }
    /**
     * Singleton access to MApiMobile controller
     * @return Controllers\MApiMobileController The *Singleton* instance
     */
    public function getMApiMobile()
    {
        return Controllers\MApiMobileController::getInstance();
    }
    /**
     * Singleton access to MApiAuth controller
     * @return Controllers\MApiAuthController The *Singleton* instance
     */
    public function getMApiAuth()
    {
        return Controllers\MApiAuthController::getInstance();
    }
    /**
     * Singleton access to MApiMobileTasksIdComments controller
     * @return Controllers\MApiMobileTasksIdCommentsController The *Singleton* instance
     */
    public function getMApiMobileTasksIdComments()
    {
        return Controllers\MApiMobileTasksIdCommentsController::getInstance();
    }
    /**
     * Singleton access to MApiMobileTasks controller
     * @return Controllers\MApiMobileTasksController The *Singleton* instance
     */
    public function getMApiMobileTasks()
    {
        return Controllers\MApiMobileTasksController::getInstance();
    }
    /**
     * Singleton access to MApiMobileClients controller
     * @return Controllers\MApiMobileClientsController The *Singleton* instance
     */
    public function getMApiMobileClients()
    {
        return Controllers\MApiMobileClientsController::getInstance();
    }
    /**
     * Singleton access to MApiMobileAttachments controller
     * @return Controllers\MApiMobileAttachmentsController The *Singleton* instance
     */
    public function getMApiMobileAttachments()
    {
        return Controllers\MApiMobileAttachmentsController::getInstance();
    }
    /**
     * Singleton access to MApiMobileChatsMessages controller
     * @return Controllers\MApiMobileChatsMessagesController The *Singleton* instance
     */
    public function getMApiMobileChatsMessages()
    {
        return Controllers\MApiMobileChatsMessagesController::getInstance();
    }
}
